RegisterCommand("me", function(source , args, rawCommand)
    local text = table.concat(args, ' ')
    text = string.sub(text,1,Config.MaxLength)
    TriggerClientEvent('3dme:me', -1, text, source, icon)
end, false)

RegisterCommand("do", function(source , args, rawCommand)
    local text = table.concat(args, ' ')
    text = string.sub(text,1,Config.MaxLength)
    TriggerClientEvent('3dme:do', -1, text, source, icon)
end, false)